# -*- coding: utf-8 -*-
"""opensrp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1etQLWYni4Fbz1CtgrxWeNBReIyoYY9nR
"""

import pandas as pd
from google.colab import drive,files
drive.mount('/content/drive')

f1=pd.read_csv(r'/content/drive/My Drive/Colab Notebooks/clients.csv', low_memory=False)
f2=pd.read_csv(r'/content/drive/My Drive/Colab Notebooks/events.csv', low_memory=False)

df = f1.merge(f2, on = "baseEntityId",how = "outer")

df.to_csv(r"Results.csv")
files.download('Results.csv')

# df=pd.merge(f1,f2, on="baseEntityId",how="outer")